apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jre83osc4-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:6ee9a3a85b77a7aade26c3ae7201dabfaecfa5b4@sha256:eb7d2f4ac5be515cf4fca007d5d60b9c6cce0054ff064e1485729d2f42aff092
          name: container-image
